/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/keyboard.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/keyboard.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.space.geometry} material={materials.keys_light} position={[-0.108, -0.017, 0.425]} rotation={[0.03, 0, 0]} />
      <mesh geometry={nodes.esc.geometry} material={materials.keys_dark} position={[-1.615, 0.009, -0.428]} rotation={[0.03, 0, 0]} />
      <mesh geometry={nodes['1'].geometry} material={materials.keys_light} position={[-1.4, 0.009, -0.428]} rotation={[0.03, 0, 0]} />
      <mesh geometry={nodes['2'].geometry} material={materials.keys_light} position={[-1.184, 0.009, -0.428]} rotation={[0.03, 0, 0]} />
      <mesh geometry={nodes['3'].geometry} material={materials.keys_light} position={[-0.969, 0.009, -0.428]} rotation={[0.03, 0, 0]} />
      <mesh geometry={nodes['4'].geometry} material={materials.keys_light} position={[-0.754, 0.009, -0.428]} rotation={[0.03, 0, 0]} />
      <mesh geometry={nodes['5'].geometry} material={materials.keys_light} position={[-0.538, 0.009, -0.428]} rotation={[0.03, 0, 0]} />
      <mesh geometry={nodes['6'].geometry} material={materials.keys_light} position={[-0.323, 0.009, -0.428]} rotation={[0.03, 0, 0]} />
      <mesh geometry={nodes['7'].geometry} material={materials.keys_light} position={[-0.107, 0.009, -0.428]} rotation={[0.03, 0, 0]} />
      <mesh geometry={nodes['8'].geometry} material={materials.keys_light} position={[0.108, 0.009, -0.428]} rotation={[0.03, 0, 0]} />
      <mesh geometry={nodes['9'].geometry} material={materials.keys_light} position={[0.323, 0.009, -0.428]} rotation={[0.03, 0, 0]} />
      <mesh geometry={nodes['0'].geometry} material={materials.keys_light} position={[0.539, 0.009, -0.428]} rotation={[0.03, 0, 0]} />
      <mesh geometry={nodes['-'].geometry} material={materials.keys_light} position={[0.754, 0.009, -0.428]} rotation={[0.03, 0, 0]} />
      <mesh geometry={nodes['+'].geometry} material={materials.keys_light} position={[0.97, 0.009, -0.428]} rotation={[0.03, 0, 0]} />
      <mesh geometry={nodes['|'].geometry} material={materials.keys_light} position={[1.185, 0.009, -0.428]} rotation={[0.03, 0, 0]} />
      <mesh geometry={nodes.del.geometry} material={materials.keys_light} position={[1.401, 0.009, -0.428]} rotation={[0.03, 0, 0]} />
      <mesh geometry={nodes['~'].geometry} material={materials.keys_light} position={[1.616, 0.009, -0.428]} rotation={[0.03, 0, 0]} />
      <mesh geometry={nodes.q.geometry} material={materials.keys_light} position={[-1.294, 0.002, -0.211]} rotation={[0.03, 0, 0]} />
      <mesh geometry={nodes.w.geometry} material={materials.keys_light} position={[-1.079, 0.002, -0.211]} rotation={[0.03, 0, 0]} />
      <mesh geometry={nodes.e.geometry} material={materials.keys_light} position={[-0.863, 0.002, -0.211]} rotation={[0.03, 0, 0]} />
      <mesh geometry={nodes.r.geometry} material={materials.keys_light} position={[-0.648, 0.002, -0.211]} rotation={[0.03, 0, 0]} />
      <mesh geometry={nodes.t.geometry} material={materials.keys_light} position={[-0.432, 0.002, -0.211]} rotation={[0.03, 0, 0]} />
      <mesh geometry={nodes.y.geometry} material={materials.keys_light} position={[-0.217, 0.002, -0.211]} rotation={[0.03, 0, 0]} />
      <mesh geometry={nodes.u.geometry} material={materials.keys_light} position={[-0.002, 0.002, -0.211]} rotation={[0.03, 0, 0]} />
      <mesh geometry={nodes.i.geometry} material={materials.keys_light} position={[0.214, 0.002, -0.211]} rotation={[0.03, 0, 0]} />
      <mesh geometry={nodes.o.geometry} material={materials.keys_light} position={[0.429, 0.002, -0.211]} rotation={[0.03, 0, 0]} />
      <mesh geometry={nodes.p.geometry} material={materials.keys_light} position={[0.645, 0.002, -0.211]} rotation={[0.03, 0, 0]} />
      <mesh geometry={nodes[''].geometry} material={materials.keys_light} position={[0.86, 0.002, -0.211]} rotation={[0.03, 0, 0]} />
      <mesh geometry={nodes._1.geometry} material={materials.keys_light} position={[1.075, 0.002, -0.211]} rotation={[0.03, 0, 0]} />
      <mesh geometry={nodes.backspace.geometry} material={materials.keys_light} position={[1.348, 0.002, -0.211]} rotation={[0.03, 0, 0]} />
      <mesh geometry={nodes.music.geometry} material={materials.keys_dark} position={[1.616, 0.002, -0.211]} rotation={[0.03, 0, 0]} />
      <mesh geometry={nodes.a.geometry} material={materials.keys_light} position={[-1.237, -0.004, 0.001]} rotation={[0.03, 0, 0]} />
      <mesh geometry={nodes.s.geometry} material={materials.keys_light} position={[-1.022, -0.004, 0.001]} rotation={[0.03, 0, 0]} />
      <mesh geometry={nodes.d.geometry} material={materials.keys_light} position={[-0.806, -0.004, 0.001]} rotation={[0.03, 0, 0]} />
      <mesh geometry={nodes.f.geometry} material={materials.keys_light} position={[-0.591, -0.004, 0.001]} rotation={[0.03, 0, 0]} />
      <mesh geometry={nodes.g.geometry} material={materials.keys_light} position={[-0.376, -0.004, 0.001]} rotation={[0.03, 0, 0]} />
      <mesh geometry={nodes.h.geometry} material={materials.keys_light} position={[-0.16, -0.004, 0.001]} rotation={[0.03, 0, 0]} />
      <mesh geometry={nodes.j.geometry} material={materials.keys_light} position={[0.055, -0.004, 0.001]} rotation={[0.03, 0, 0]} />
      <mesh geometry={nodes.k.geometry} material={materials.keys_light} position={[0.271, -0.004, 0.001]} rotation={[0.03, 0, 0]} />
      <mesh geometry={nodes.l.geometry} material={materials.keys_light} position={[0.486, -0.004, 0.001]} rotation={[0.03, 0, 0]} />
      <mesh geometry={nodes.semicolon.geometry} material={materials.keys_light} position={[0.701, -0.004, 0.001]} rotation={[0.03, 0, 0]} />
      <mesh geometry={nodes.apostrophe.geometry} material={materials.keys_light} position={[0.917, -0.004, 0.001]} rotation={[0.03, 0, 0]} />
      <mesh geometry={nodes.tab.geometry} material={materials.keys_light} position={[-1.563, 0.002, -0.211]} rotation={[0.03, 0, 0]} />
      <mesh geometry={nodes.none.geometry} material={materials.keys_light} position={[1.616, -0.004, 0.001]} rotation={[0.03, 0, 0]} />
      <mesh geometry={nodes.z.geometry} material={materials.keys_light} position={[-1.13, -0.011, 0.214]} rotation={[0.03, 0, 0]} />
      <mesh geometry={nodes.x.geometry} material={materials.keys_light} position={[-0.914, -0.011, 0.214]} rotation={[0.03, 0, 0]} />
      <mesh geometry={nodes.c.geometry} material={materials.keys_light} position={[-0.699, -0.011, 0.214]} rotation={[0.03, 0, 0]} />
      <mesh geometry={nodes.v.geometry} material={materials.keys_light} position={[-0.483, -0.011, 0.214]} rotation={[0.03, 0, 0]} />
      <mesh geometry={nodes.b.geometry} material={materials.keys_light} position={[-0.268, -0.011, 0.214]} rotation={[0.03, 0, 0]} />
      <mesh geometry={nodes.n.geometry} material={materials.keys_light} position={[-0.053, -0.011, 0.214]} rotation={[0.03, 0, 0]} />
      <mesh geometry={nodes.m.geometry} material={materials.keys_light} position={[0.163, -0.011, 0.214]} rotation={[0.03, 0, 0]} />
      <mesh geometry={nodes[','].geometry} material={materials.keys_light} position={[0.378, -0.011, 0.214]} rotation={[0.03, 0, 0]} />
      <mesh geometry={nodes._2.geometry} material={materials.keys_light} position={[0.594, -0.011, 0.214]} rotation={[0.03, 0, 0]} />
      <mesh geometry={nodes._3.geometry} material={materials.keys_light} position={[0.809, -0.011, 0.214]} rotation={[0.03, 0, 0]} />
      <mesh geometry={nodes.enter.geometry} material={materials.keys_dark} position={[1.265, -0.004, 0.001]} rotation={[0.03, 0, 0]} />
      <mesh geometry={nodes.shift_r.geometry} material={materials.keys_light} position={[1.104, -0.011, 0.213]} rotation={[0.03, 0, 0]} />
      <mesh geometry={nodes.shift_l.geometry} material={materials.keys_light} position={[-1.481, -0.011, 0.214]} rotation={[0.03, 0, 0]} />
      <mesh geometry={nodes.caps.geometry} material={materials.keys_light} position={[-1.536, -0.004, 0.001]} rotation={[0.03, 0, 0]} />
      <mesh geometry={nodes.ctrl_l.geometry} material={materials.keys_light} position={[-1.563, -0.017, 0.425]} rotation={[0.03, 0, 0]} />
      <mesh geometry={nodes.alt_l.geometry} material={materials.keys_light} position={[-1.021, -0.017, 0.425]} rotation={[0.03, 0, 0]} />
      <mesh geometry={nodes.alt_r.geometry} material={materials.keys_light} position={[0.805, -0.017, 0.425]} rotation={[0.03, 0, 0]} />
      <mesh geometry={nodes.none001.geometry} material={materials.keys_light} position={[1.616, -0.011, 0.213]} rotation={[0.03, 0, 0]} />
      <mesh geometry={nodes.up.geometry} material={materials.keys_light} position={[1.401, -0.011, 0.213]} rotation={[0.03, 0, 0]} />
      <mesh geometry={nodes.down.geometry} material={materials.keys_light} position={[1.401, -0.017, 0.425]} rotation={[0.03, 0, 0]} />
      <mesh geometry={nodes.left.geometry} material={materials.keys_light} position={[1.183, -0.017, 0.425]} rotation={[0.03, 0, 0]} />
      <mesh geometry={nodes.right.geometry} material={materials.keys_light} position={[1.616, -0.017, 0.425]} rotation={[0.03, 0, 0]} />
      <mesh geometry={nodes['super'].geometry} material={materials.keys_dark} position={[-1.294, -0.017, 0.425]} rotation={[0.03, 0, 0]} />
      <mesh geometry={nodes.Base.geometry} material={materials.base} />
      <mesh geometry={nodes.base_back.geometry} material={materials.base} position={[0, -0.09, -0.733]} />
      <mesh geometry={nodes.typeC.geometry} material={materials.port} position={[0, -0.09, -0.733]} scale={1.146} />
    </group>
  )
}

useGLTF.preload('/keyboard.glb')
